# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine

# Enable pnpm via corepack
RUN corepack enable

# Create app directory
WORKDIR /app

# Copy project files
COPY . .

# Install dependencies without frozen lockfile
RUN pnpm install --no-frozen-lockfile

# Build all packages
RUN pnpm -r build

# Set working directory to MCP server package
WORKDIR /app/packages/mcp-server

# Default command
ENTRYPOINT ["node", "dist/server.js"]
